# Generated by Django 5.2.4 on 2025-07-03 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='start_date',
        ),
    ]
